jms_security_extra:
    expressions: true

security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        main:
            pattern: ^/

            anonymous: true

            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
                always_use_default_target_path: true

            logout:
                path: fos_user_security_logout
